name: Setup dependencies
description: Setup dependencies required to run pipeline
inputs:
  git_token:
    required: true
    description: "Team orange git token"
  
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Git token to git url
      run: git config --global url."https://oauth2:${{ inputs.git_token }}@github.com/recognizegroup".insteadOf https://github.com/recognizegroup
      shell: bash
    - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      shell: bash
    - name: Setup
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.59.1/terragrunt_linux_amd64
        mv terragrunt_linux_amd64 terragrunt
        chmod +x terragrunt
        mv terragrunt /usr/local/bin
      shell: bash
    - name: install Terraform
      run: | 
        wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
        unzip -o terraform_1.9.8_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version 
      shell: bash