name: Setup dependencies
description: Setup dependencies required to run pipeline
inputs:
  git_token:
    required: true
    description: "Team orange git token"
  
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Git token to git url
      run: git config --global url."https://oauth2:${{ inputs.git_token }}@github.com/recognizegroup".insteadOf https://github.com/recognizegroup
      shell: bash
    - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      shell: bash
    - name: Setup
      run: |
        brew tap-new pipeline/terragrunt
        brew extract --version 0.66.9 composer pipeline/terragrunt
        brew install terragrunt@v0.66.9
      
      shell: bash