name: Terragrunt Apply
description: Runs Terragrunt apply and reports failure if occurs 
inputs:
  webhook:
    required: true
    description: "teams webhook"
  terragrunt_download_directory:
    required: true
    description: "Terragrunt download directory"
  working_directory:
    required: false
    default: .
    description: "Location where to execute terragrunt apply command"

runs:
  using: composite
  steps:
    - name: Clean up disk space and create Terraform Download Directory
      run: |
        # Clean up disk space
        sudo rm -rf /tmp/* 2>/dev/null || true
        sudo rm -rf /var/tmp/* 2>/dev/null || true
        sudo rm -rf ~/.cache/* 2>/dev/null || true
        sudo rm -rf /home/runner/.cache/* 2>/dev/null || true
        
        # Clean up old terragrunt downloads
        rm -rf ${{ inputs.terragrunt_download_directory }}/* --force 2>/dev/null || true
        mkdir --parents ${{ inputs.terragrunt_download_directory }}
        
        # Show available disk space
        df -h
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - name: Terragrunt Apply
      run: |
        terragrunt run-all apply --non-interactive --terragrunt-parallelism 5
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - name: Clean up after deployment
      run: |
        # Clean up terragrunt cache and temporary files
        rm -rf ${{ inputs.terragrunt_download_directory }}/* --force 2>/dev/null || true
        rm -rf .terraform/* --force 2>/dev/null || true
        rm -rf .terragrunt-cache/* --force 2>/dev/null || true
        
        # Show final disk space
        df -h
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - name: Notify about failures
      if: ${{ failure() }}
      run: |
        cat << EOF > message.json
        {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"Pipeline failed!","themeColor":"ff0000","title":"$GITHUB_REPOSITORY pipeline failed 💢!","sections":[{"facts":[{"name":"Repository:","value":"$GITHUB_REPOSITORY"},{"name":"Branch:","value":"$GITHUB_REF_NAME"},{"name":"Commit:","value":"$GITHUB_SHA"}]}],"potentialAction":[{"@type":"OpenUri","name":"View on GitHub","targets":[{"os":"default","uri":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}]}]}
        EOF
        curl -X POST ${{ inputs.webhook }} --header 'Content-Type: application/json' -d @message.json
      shell: bash