name: PR Title Checker
on:
  workflow_call:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize

inputs:
  regex:
    required: false
    description: "teams webhook"
    default: ".*(ab|AB)#[0-9]+.*"

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Echo value
        run: echo ${{ inputs.regex }}
      - name: regex check
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: ".*(ab|AB)#[0-9]+.*" # Regex the title should match ab#(number) or AB#(number).
          helpMessage: "PR title check failed: AB# must be included somewhere in the PR title!'"